export const ADD_MOVIE = 'saveMovie';
export const UPDATE_MOVIE = 'updateMovie';
export const DELETE_MOVIE ='deleteMovie';
export const CLEAR_ALL_MOVIES='clearAllMovies';
export const ADD_SERIES ='addSeries';
export const UPDATE_SERIES ='updateSeries';
export const DELETE_SERIES ='deleteSeries';
export const CLEAR_ALL_SERIES='clearAllSeries';
export const UPDATE_START='updateStart';